openapi: 3.0.0
info:
 title: Test  API
 description: |
  API documentation for managing test operations, including creation, updates, and more.
 version: "1.0.0"
servers:
  - url: localhost:3000/api/docs
    description: Development Server
paths: 
  "/tests":
    post: 
      tags: 
        - tests 
      summary: Create test data
      description: Add a new test to the system
      requestBody:
        content: 
          "application/json":
            schema:
              allOf:
                - $ref: "./components/schemas/TestData.yaml"
      responses:
        "201":
          description: Success Response 
          content: 
            "application/json":
              schema:
                allOf:
                  - $ref: "./components/responses.yaml#/components/schemas/BaseResponse"
                  - type: object 
                    properties:
                      data: 
                        $ref: "./components/schemas/TestData.yaml"
    get: 
      summary: Retrieve all test data
      description: Fetch a list of all available test data
      responses: 
        "200":
          description: Fetch a list of all available test data
          content: 
            "application/json":
              schema:
                allOf:
                  - $ref: "./components/responses.yaml#/components/schemas/BaseResponse"
                  - type: object 
                    properties: 
                      data:
                        type: array 
                        items: 
                          $ref: "./components/schemas/TestData.yaml"
  "/tests/{id}":
    get: 
      summary: Retrieve a specific test data
      description: Fetch detailed information about a specific test using its unique identifier
      parameters:
        - name: id 
          in: path 
          required: true 
          description: The unique identifier for the test
          schema:
            type: string 
      responses: 
        "200":
          description: success response 
          content: 
            "application/json":
              schema:
                allOf:
                  - $ref: "./components/responses.yaml#/components/schemas/BaseResponse"
                  - type: object 
                    properties:
                      data: 
                        $ref: "./components/schemas/TestData.yaml"
